### ISSUE TITLE
Nuget package

### ISSUE THREAD

**Issue by mdabros** [ttustonic/LightGBMSharp#2]
Hi @ttustonic,

Great work creating this C# wrapper for LightGBM! 
Would you be willing to add a nuget package for the library?

best regards
Mads

**Comment by ttustonic** [comment]
Thanks!
I would be. I'll look at it in the next few days.

**Comment by mdabros** [comment]
Sounds great - Thanks!

**Comment by ttustonic** [comment]
Here it is.
https://www.nuget.org/packages/LightGBMSharp/0.1.0
________________________________

**Comment by mdabros** [comment]
Great thank you very much!
