### ISSUE TITLE
Excited with code xxxx during Prediction

### ISSUE THREAD

**Issue by wil70** [ttustonic/LightGBMSharp#5]
Hello, 

I've trained a LightGBM model using the C/C++ version with the CLI and successfully exported the model. My objective is to perform predictions from a C# program. I've written the following C# code:

```
Booster booster = new Booster(@"my model from LightGBM CLI");
double[] desiredOutput = null;
var inputData = loadInputs(@"my testing data", out desiredOutput);
var prediction = booster.Predict(inputData);
Console.WriteLine("Prediction: " + prediction);
Console.ReadLine();
```
However, I encounter an error when executing the line "var prediction = booster.Predict(inputData);"

```
Error message on the console: (process 25920) exited with code -1073741819.
Error message in VS Output: has exited with code 3221225477 (0xc0000005) 'Access violation'.
```

Could you please provide guidance on how to resolve this issue?

Thank you,
Wil

I use LightGBM 4.1.0 and LightGBMSharp 0.1.0

**Comment by ttustonic** [comment]
I'm no longeer using this (should probably put it in archive), so I really don't know. 
The last version of LightGBM that I used is 2.3.1, so perhaps you could try with that. Probably the data structures or method parameters have changed since then.

**Comment by wil70** [comment]
Hello James,

**Regarding ML.Net,** I noticed that WrappedLightGbmBooster.cs includes EvalTrain(), which appears to take the entire dataset. However, my intention is to train with LightGBM CLI/C++ and then export the model for use in any language, such as C#. I'm considering whether I can call the following code directly:


```
double[] res = new double[1];
fixed (double* ptr = res)
    LightGbmInterfaceUtils.Check(WrappedLightGbmInterface.BoosterGetEval(Handle, dataIdx, ref outLen, ptr));
```
I expected  this to be a basic use case? if true, we should well-document it and it should be very easy to use.



**As for the 'task==convert_model,'** I'm simultaneously trying to use it in LightGBM, which generates the gbdt_prediction.cpp file. I've set up a small Visual Studio 2020 project to generate a DLL, with the hope of being able to call this DLL from C#. However, I'm encountering an issue with linking:

less
Copy code
------ Build started: Project: LightGBM_TrainingResults_Cpp2CSharp, Configuration: Debug x64 ------
x64\Debug\gbdt_prediction.obj : warning LNK4042: object specified more than once; extras ignored
Creating library C:\Users\wilhe\source\repos\LightGBM_TrainingResults_Cpp2CSharp\x64\Debug\LightGBM_TrainingResults_Cpp2CSharp.lib and object C:\Users\wilhe\source\repos\LightGBM_TrainingResults_Cpp2CSharp\x64\Debug\LightGBM_TrainingResults_Cpp2CSharp.exp
gbdt_prediction.obj : error LNK2019: unresolved external symbol "public: void __cdecl LightGBM::Metadata::InitByReference(int,class LightGBM::Metadata const *)" (?InitByReference@Metadata@LightGBM@@QEAAXHPEBV12@@Z) referenced in function "public: void __cdecl LightGBM::Dataset::InitByReference(int,class LightGBM::Dataset const *)" (?InitByReference@Dataset@LightGBM@@QEAAXHPEBV12@@Z)
gbdt_prediction.obj : error LNK2019: unresolved external symbol "public: void __cdecl LightGBM::Metadata::Init(int,int,int,int,int)" (?Init@Metadata@LightGBM@@QEAAXHHHHH@Z) referenced in function "public: void __cdecl LightGBM::Dataset::InitStreaming(int,int,int,int,int,int,int)" (?InitStreaming@Dataset@LightGBM@@QEAAXHHHHHHH@Z)
C:\Users\wilhe\source\repos\LightGBM_TrainingResults_Cpp2CSharp\x64\Debug\LightGBM_TrainingResults_Cpp2CSharp.dll : fatal error LNK1120: 2 unresolved externals
Done building project "LightGBM_TrainingResults_Cpp2CSharp.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
========== Build started at 9:18 PM and took 01.289 seconds ==========
Your assistance in resolving these issues would be greatly appreciated.

Thanks,

Wilhelm
